/**
  * Uniquifier is a simple class that allows the generation of unique, arbitrary
  * string lengths that are numerical/integers.
  *
  * Date: 27 October 2018
  * Author: Matthew Morgan
  */

package src;

import java.util.ArrayList;

public class Uniquifier {
  // L is the list of all numbers already generated by this uniquifier
  // len is the length of each number generated by this uniquifier
  private ArrayList<String> L;
  private int len;

  public Uniquifier(int num) { len = num; L = new ArrayList<>(); }

  /** reserve(str) reserves the numerical string specified in this uniquifier */

  public void reserve(String str) { L.add(str); }

  /** setList(newL) replaces the list of numbers this uniquifier has generated
    * with the list specified as the argument. */

  public void setList(ArrayList<String> newL) { L = newL; }

  /** get() returns a new, unique number of this uniquifier's length according
    * to the list of numbers generated by this uniquifier. */

  public String get() {
    String tmp;

    do { tmp = Helper.randomDigits(len); }
    while(L.contains(tmp));

    L.add(tmp);
    return tmp;
  }
}